### ISSUE TITLE
Environment variables loaded from file

### ISSUE THREAD

**Issue by nwhite89** [SC5/serverless-mocha-plugin#37]
Looks like there is a bug with the way that environment variables are loaded I'm not sure if it's because tests are run to early. But `serverless` allows for loading Env vars from a variable https://serverless.com/blog/serverless-v1.2.0/?utm_source=Newsletter&utm_medium=Email&utm_campaign=v1.2%20release. Such as

```yml
functions:
  myFunction:
    environment:
      apiKey: ${file(../keys.yml):apiKey}
```

It looks like that when a test is being run it's still being provided `${file(../keys.yml):apiKey}` rather than the variable itself.

**Comment by nwhite89** [comment]
Perhaps using this https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js#L25 instead of the current would be better?

**Comment by laardee** [comment]
@nwhite89 thanks, I noticed this also couple days ago, I'll start working on this ASAP.

**Comment by nwhite89** [comment]
👍 that's great @laardee have been waiting to move to use this due to `serverless-offline` that's finally working and then came against builds going red and had no clue what was going on lol.

**Comment by mpuittinen** [comment]
Merged fix to master and published version 1.3.2 of the plugin.

**Comment by jloveland** [comment]
I am still having this issue in my project.

The environment variables are coming in fine when I use the following serverless test:
`sls invoke local -f getPlaces -p test/event.json`

However, when I use the mocha test, I don't get the environment variables.
`sls invoke test`

my secrets are kept in a file called `secrets.dev.yml`

in `serverless.yml` I have:
```
custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 512 # optional, default is 1024
  timeout: 10 # optional, default is 6
  stage: dev
  region: us-east-1
  environment:
    API_KEY: ${self:custom.secrets.API_KEY}
```
I am using serverless 1.5.0 and serverless-mocha-plugin 1.3.2
